modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/simple-woodcutter"
license = "MIT"

[[mods]]
modId = "simple_woodcutter"
version = "${version}"
displayName = "Simple Woodcutter"
authors = "Zebatek"
description = "This mod adds a simple vanilla-like woodcutter. It's easy to craft and it has over 100 built-in recipes. You can also use it in your own mod, for example to add custom recipes to your custom wood etc."

logoFile = "icon.png"

[[dependencies.simple_woodcutter]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simple_woodcutter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.5)"
ordering = "NONE"
side = "BOTH"

